export const ADD_TODO = 'add_todo'
export const DELETE_TODO = 'delete_todo'
export const SELECTED_ALL_TODOS = 'select_all_todos'
export const CLEAR_COMPLETED_TODOS = 'clear_completed_todos'
export const RECEIVE_TODOS = 'receive_todos'